spring:
  application:
    name: AIExpertDecisionServer
  # 环境切换
  profiles:
    active: local # 激活 local profile
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://127.0.0.1:3306/base?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://39.103.63.72:3306/base?characterEncoding=utf8&useSSL=false
    username: hysen
    password: Hysen*5_zhen
    type: com.alibaba.druid.pool.DruidDataSource  #底层使用druid连接池
    druid:
      initial-size: 5  # 初始化连接数大小
      max-active: 10  # 最大连接数
      min-idle: 3   # 最小连接数
      # 连接等待超时的时间
      max-wait: 2000 # 如果连接都被占用，最大等待时间60000ms=1min
      validation-query: SELECT NOW() #通过从续表查询来监控是否连接数据库，语句执行能连接，语句不执行没连接
      # 配置一个连接在池中最小空闲的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      # 开启SQL监控、防火墙监控、日志监控
      filters: stat,wall,slf4j
      # 配置DruidStatViewServlet
      stat-view-servlet:
        # 登录名
        login-username: admin
        # 登录密码
        login-password: admin
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1  # 本机和设置的ip可以访问后台管理界面
        reset-enable: false # 不要重置
        # 启用控制台-后台管理界面，必须启用，否则访问界面会404
        enabled: true

  ai:
    openai:
      # 默认的 OpenAI 兼容客户端配置 (SiliconFlow Qwen)
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: Qwen/Qwen3-8B
          temperature: 1.3

# 自定义LLM提供商的配置
custom:
  ai:
    providers:
      # DeepSeek模型配置
      deepseek:
        base-url: https://api.siliconflow.cn
        api-key: ${DEEPSEEK_API_KEY} # 占位符，实际值在application-local.yml中
        chat:
          options:
            model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
            temperature: 1.3
      
      # 另一个提供商(THUDM)模型配置
      anotherprovider:
        base-url: https://api.siliconflow.cn
        api-key: ${ANOTHERPROVIDER_API_KEY} # 占位符，实际值在application-local.yml中
        chat:
          options:
            model: THUDM/GLM-Z1-9B-0414
            temperature: 1.3

server:
  port: 5002
  servlet:
    context-path: /AIExpertDecisionServer

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: institute.pojo #给所有pojo类起别名

# 当没有logback.xml文件时
# logging:
#   level:
#     '[top.hysenw.mapper]': trace

